Repository Ollamy/Ollamy, pull requests merged in 2024-10, with the labels that each got.

#236 Mobile app
  packages/service-backend/prisma/migrations/20240913010624_events_and_badge_triggers/migration.sql
  packages/service-backend/prisma/schema.prisma
  packages/service-backend/setup/database_schema_create.sql
  packages/service-backend/setup/database_schema_delete.sql
  packages/service-backend/src/app.module.ts
  packages/service-backend/src/badge/badge.controller.ts
  packages/service-backend/src/badge/badge.dto.ts
  packages/service-backend/src/badge/badge.service.ts
  packages/service-backend/src/course/course.service.ts
  packages/service-backend/src/event/event.controller.ts
  packages/service-backend/src/event/event.dto.ts
  packages/service-backend/src/event/event.module.ts
  packages/service-backend/src/event/event.service.ts
  packages/service-backend/src/lesson/lesson.service.ts
  packages/service-backend/src/question/question.dto.ts
  packages/service-backend/src/section/section.service.ts
  packages/service-backend/src/session/session.service.ts
  packages/service-backend/src/tests/data/badge.data.ts
  packages/service-backend/src/tests/unit_tests/user.spec.ts
  packages/service-backend/src/user/user.service.ts
  packages/service-backend/swagger.json
  packages/service-maker/src/services/api/out/.openapi-generator/FILES
  packages/service-maker/src/services/api/out/apis/EventApi.ts
  packages/service-maker/src/services/api/out/apis/index.ts
  packages/service-maker/src/services/api/out/models/index.ts
  packages/service-mobile-app/assets/sound/unlock.mp3
  packages/service-mobile-app/package.json
  packages/service-mobile-app/src/components/Modal/Events/Unlockbadges/index.tsx
  packages/service-mobile-app/src/components/Modal/Events/eventFactory.tsx
  packages/service-mobile-app/src/components/Modal/Events/index.tsx
  packages/service-mobile-app/src/components/Modal/Events/type.ts
  packages/service-mobile-app/src/components/layout/AppSafeArea/AppSafeArea.tsx
  packages/service-mobile-app/src/components/layout/BottomBar/BottomBar.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/LessonsList/LessonsList.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/SectionsList/SectionsList.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/factory/QuizFactory.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/factory/components/OrderChoice/DragDrop.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/factory/components/OrderChoice/DragDropTarget.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/factory/components/OrderChoice/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/factory/components/SquareChoice.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/image.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/questionBonus.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/questionTimer.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/questionTitle.tsx
  packages/service-mobile-app/src/services/question/question.dto.ts
  packages/service-mobile-app/src/services/user/user.ts
  packages/service-mobile-app/yarn.lock
Labels: enhancement

#109 App build serving backend
  .env.example
  .github/workflows/build.yml
  .github/workflows/test.yml
  docker-compose.yml
  packages/service-backend/package.json
  packages/service-backend/src/app.module.ts
  packages/service-backend/src/main.ts
  packages/service-backend/src/mobileApp/mobileApp.controller.ts
  packages/service-backend/src/mobileApp/mobileApp.dto.ts
  packages/service-backend/src/mobileApp/mobileApp.module.ts
  packages/service-backend/src/mobileApp/mobileAppService.ts
  packages/service-backend/src/setup.ts
  packages/service-backend/swagger.json
  packages/service-maker/src/pages/UserProfile/UserGeneralSettings/UserGeneralSettings.tsx
  packages/service-maker/src/services/api/index.tsx
  packages/service-maker/src/services/api/out/.openapi-generator/FILES
  packages/service-maker/src/services/api/out/apis/MobileAppApi.ts
  packages/service-maker/src/services/api/out/apis/index.ts
  packages/service-maker/src/services/api/out/models/index.ts
  packages/service-maker/src/services/api/routes/mobileApp.tsx
  packages/service-mobile-app/yarn.lock
Labels: enhancement

#259 AI generate multiple type of questions
  packages/service-backend/public/mobile_build/.gitkeep
  packages/service-backend/src/ai/ai.controller.ts
  packages/service-backend/src/ai/ai.dto.ts
  packages/service-backend/src/ai/ai.service.ts
  packages/service-backend/src/mobileApp/mobileAppService.ts
  packages/service-backend/swagger.json
  packages/service-maker/src/services/api/out/apis/AiApi.ts
  packages/service-maker/src/services/api/out/models/index.ts
Labels: Back

#261 Fix hp system for backend and add log for debug
  packages/service-backend/src/cron/cron.service.ts
  packages/service-backend/src/session/session.service.ts
Labels: bug, Back

#258 Change app icon
  packages/service-mobile-app/app.json
  packages/service-mobile-app/assets/app-icon.png
  packages/service-mobile-app/assets/icon.png
Labels: enhancement
