Repository Ollamy/Ollamy, pull requests merged in 2024-02, with the labels that each got.

#98 97 oll 299 image system backend public url implementation
  .github/workflows/test.yml
  .gitignore
  docker-compose.yml
  packages/service-backend/package.json
  packages/service-backend/prisma/migrations/20240122045517_/migration.sql
  packages/service-backend/prisma/migrations/20240122053535_/migration.sql
  packages/service-backend/prisma/migrations/20240205195422_image/migration.sql
  packages/service-backend/prisma/schema.prisma
  packages/service-backend/public/.gitkeep
  packages/service-backend/src/app.module.ts
  packages/service-backend/src/course/course.controller.ts
  packages/service-backend/src/course/course.spec.ts
  packages/service-backend/src/picture/picture.service.ts
  packages/service-backend/src/question/question.spec.ts
  packages/service-backend/swagger.json
  packages/service-maker/src/services/api/out/apis/CourseApi.ts
  yarn.lock
Labels: Back

#82 68 oll 274 mobile main dashboard code
  package.json
  packages/service-mobile-app/.babelrc
  packages/service-mobile-app/.env.example
  packages/service-mobile-app/.gitignore
  packages/service-mobile-app/app.json
  packages/service-mobile-app/assets/completed.png
  packages/service-mobile-app/assets/lock.png
  packages/service-mobile-app/assets/yellow-right-arrow.png
  packages/service-mobile-app/eas.json
  packages/service-mobile-app/metro.config.js
  packages/service-mobile-app/package.json
  packages/service-mobile-app/src/App.tsx
  packages/service-mobile-app/src/components/LessonListItem/index.tsx
  packages/service-mobile-app/src/components/ProgressBar.tsx
  packages/service-mobile-app/src/components/SectionHeader/index.tsx
  packages/service-mobile-app/src/components/VerticalProgressBar/index.tsx
  packages/service-mobile-app/src/components/bottomBar/index.tsx
  packages/service-mobile-app/src/components/buttons/CourseRowButton.tsx
  packages/service-mobile-app/src/components/buttons/YesNoButton/index.tsx
  packages/service-mobile-app/src/components/safeArea/AppSafeArea.tsx
  packages/service-mobile-app/src/components/topBar/index.tsx
  packages/service-mobile-app/src/pages/authentication/Routes.tsx
  packages/service-mobile-app/src/pages/authentication/login/index.tsx
  packages/service-mobile-app/src/pages/authentication/register/index.tsx
  packages/service-mobile-app/src/pages/chat/Routes.tsx
  packages/service-mobile-app/src/pages/chat/index.tsx
  packages/service-mobile-app/src/pages/courses/Routes.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/section/index.tsx
  packages/service-mobile-app/src/pages/courses/joinCourse/index.tsx
  packages/service-mobile-app/src/pages/home/Routes.tsx
  packages/service-mobile-app/src/pages/home/index.tsx
  packages/service-mobile-app/src/pages/profile/Routes.tsx
  packages/service-mobile-app/src/pages/profile/index.tsx
  packages/service-mobile-app/src/pages/splashScreen/Routes.tsx
  packages/service-mobile-app/src/pages/splashScreen/index.tsx
  packages/service-mobile-app/src/services/api.ts
  packages/service-mobile-app/src/services/auth/auth.dto.ts
  packages/service-mobile-app/src/services/auth/auth.ts
  packages/service-mobile-app/src/services/course/course.dto.ts
  packages/service-mobile-app/src/services/course/course.ts
  packages/service-mobile-app/src/services/lesson/lesson.dto.ts
  packages/service-mobile-app/src/services/lesson/lesson.ts
  packages/service-mobile-app/src/services/section/section.dto.ts
  packages/service-mobile-app/src/services/section/section.ts
  packages/service-mobile-app/src/services/user.ts
  packages/service-mobile-app/src/services/user/user.dto.ts
  packages/service-mobile-app/src/services/user/user.ts
  packages/service-mobile-app/src/theme/theme.ts
  packages/util-design-system/package.json
  yarn.lock
Labels: Frontend

#104 Oll 296 mobile features full audit
  .github/workflows/mobile-lint.yml
  packages/service-mobile-app/.eslintrc.yaml
  packages/service-mobile-app/.prettierrc
  packages/service-mobile-app/package.json
  packages/service-mobile-app/src/App.tsx
  packages/service-mobile-app/src/components/Buttons/CourseRowButton/CourseRowButton.tsx
  packages/service-mobile-app/src/components/Buttons/CustomIconButton/CustomIconButton.tsx
  packages/service-mobile-app/src/components/Buttons/IconButton/IconButton.tsx
  packages/service-mobile-app/src/components/Buttons/YesNoButton/YesNoButton.tsx
  packages/service-mobile-app/src/components/LessonListItem/LessonListItem.tsx
  packages/service-mobile-app/src/components/LessonListItem/index.tsx
  packages/service-mobile-app/src/components/ProgressBar/ProgressBar.tsx
  packages/service-mobile-app/src/components/SectionHeader/SectionHeader.tsx
  packages/service-mobile-app/src/components/SectionHeader/index.tsx
  packages/service-mobile-app/src/components/VerticalProgressBar/VerticalProgressBar.tsx
  packages/service-mobile-app/src/components/VerticalProgressBar/index.tsx
  packages/service-mobile-app/src/components/bottomBar/index.tsx
  packages/service-mobile-app/src/components/buttons/CourseRowButton.tsx
  packages/service-mobile-app/src/components/buttons/YesNoButton/index.tsx
  packages/service-mobile-app/src/components/buttons/customIconButton/index.tsx
  packages/service-mobile-app/src/components/buttons/iconButton/index.tsx
  packages/service-mobile-app/src/components/layout/AppSafeArea/AppSafeArea.tsx
  packages/service-mobile-app/src/components/layout/BottomBar/BottomBar.tsx
  packages/service-mobile-app/src/components/layout/TopBar/TopBar.tsx
  packages/service-mobile-app/src/components/safeArea/AppSafeArea.tsx
  packages/service-mobile-app/src/components/topBar/index.tsx
  packages/service-mobile-app/src/features/auth/authSlice.ts
  packages/service-mobile-app/src/pages/authentication/login/index.tsx
  packages/service-mobile-app/src/pages/authentication/register/index.tsx
  packages/service-mobile-app/src/pages/chat/index.tsx
  packages/service-mobile-app/src/pages/courses/JoinCourse/JoinCourse.tsx
  packages/service-mobile-app/src/pages/courses/Routes.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/CourseDashboard/CourseDashboard.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/SectionDashboard/SectionDashboard.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/section/index.tsx
  packages/service-mobile-app/src/pages/courses/joinCourse/index.tsx
  packages/service-mobile-app/src/pages/courses/types.ts
  packages/service-mobile-app/src/pages/home/index.tsx
  packages/service-mobile-app/src/pages/profile/Routes.tsx
  packages/service-mobile-app/src/pages/profile/index.tsx
  packages/service-mobile-app/src/pages/splashScreen/index.tsx
  packages/service-mobile-app/src/services/api.ts
  packages/service-mobile-app/src/services/auth/auth.dto.ts
  packages/service-mobile-app/src/services/auth/auth.ts
  packages/service-mobile-app/src/services/course/course.dto.ts
  packages/service-mobile-app/src/services/course/course.ts
  packages/service-mobile-app/src/services/lesson/lesson.dto.ts
  packages/service-mobile-app/src/services/lesson/lesson.ts
  packages/service-mobile-app/src/services/section/section.dto.ts
  packages/service-mobile-app/src/services/section/section.ts
  packages/service-mobile-app/src/services/user/user.dto.ts
  packages/service-mobile-app/src/services/user/user.ts
  packages/service-mobile-app/src/store.ts
  packages/service-mobile-app/src/theme/button/button.theme.ts
  packages/service-mobile-app/src/theme/input/input.theme.ts
  packages/service-mobile-app/src/theme/text/text.theme.ts
  packages/service-mobile-app/src/theme/theme.ts
  packages/service-mobile-app/src/utils/loadEnv.ts
Labels: Archi, Improvement

#70 Mobile - Lesson lecture
  packages/service-backend/src/lesson/lesson.controller.ts
  packages/service-backend/src/lesson/lesson.service.ts
  packages/service-backend/src/main.ts
  packages/service-backend/src/picture/picture.service.ts
  packages/service-backend/src/question/question.dto.ts
  packages/service-maker/src/services/api/out/apis/LessonApi.ts
  packages/service-mobile-app/assets/icons/badCheck.png
  packages/service-mobile-app/assets/icons/cup.png
  packages/service-mobile-app/assets/icons/fail.png
  packages/service-mobile-app/assets/icons/goodCheck.png
  packages/service-mobile-app/assets/icons/star.png
  packages/service-mobile-app/package.json
  packages/service-mobile-app/src/components/ErrorPage/ErrorPage.tsx
  packages/service-mobile-app/src/components/ProgressBar/ProgressBar.tsx
  packages/service-mobile-app/src/components/buttons/textButton/index.tsx
  packages/service-mobile-app/src/components/layout/AppSafeArea/AppSafeArea.tsx
  packages/service-mobile-app/src/components/topBarContainer/index.tsx
  packages/service-mobile-app/src/pages/courses/Routes.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/CourseDashboard/CourseDashboard.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/SectionDashboard/SectionDashboard.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/lecture/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/index.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/questionDifficulty.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/question/questionTitle.tsx
  packages/service-mobile-app/src/pages/courses/dashboard/lesson/quiz/result/index.tsx
  packages/service-mobile-app/src/services/api.ts
  packages/service-mobile-app/src/services/lesson/lesson.dto.ts
  packages/service-mobile-app/src/services/lesson/lesson.ts
  packages/service-mobile-app/src/services/question/question.dto.ts
  packages/service-mobile-app/src/services/question/question.ts
  yarn.lock
Labels: Frontend
